# Spring Boot Application Name
spring.application.name=springboot-h2-ci-cd

# Server Port
server.port=8081

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ensure schema and data scripts are executed
spring.datasource.initialization-mode=always
spring.sql.init.mode=always


# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator for Monitoring
management.endpoints.web.exposure.include=*
management.metrics.export.prometheus.enabled=true